# Generated by Django 5.2.1 on 2025-06-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=110, null=True)),
                ('address', models.CharField(max_length=110, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_Intrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=110, null=True)),
                ('address', models.CharField(max_length=110, null=True)),
                ('course', models.CharField(choices=[('web', 'Web Development'), ('design', 'UI/UX Design'), ('android_dev', 'Android Development'), ('IOS_dev', 'IOS Development'), ('solar', 'Solar Installation'), ('electronics', 'Electronics')], max_length=110)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('residential_address', models.TextField()),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_relationship', models.CharField(max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('highest_qualification', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=150)),
                ('graduation_year', models.CharField(max_length=4)),
                ('field_of_study', models.CharField(max_length=100)),
                ('relevant_skills', models.TextField(blank=True)),
            ],
        ),
    ]
