# Generated by Django 5.2.1 on 2025-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_soft_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classMode',
            field=models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Online', 'Online')], max_length=110),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('UI/UX Design', 'UI/UX Design'), ('Android Development', 'Android Development'), ('IOS Development', 'IOS Development'), ('Solar Installation', 'Solar Installation'), ('Electronics', 'Electronics')], default='Invalid', max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='lga',
            field=models.CharField(max_length=100),
        ),
    ]
