# Generated by Django 5.2.1 on 2025-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_soft_app', '0002_student_classmode_student_course_student_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
