# Generated by Django 5.2.1 on 2025-06-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_soft_app', '0003_alter_student_lga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classMode',
            new_name='class_mode',
        ),
    ]
