# Generated by Django 5.2.1 on 2025-06-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_soft_app', '0004_rename_classmode_student_class_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_mode',
            field=models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Online', 'Online')], default='Onsite', max_length=110),
        ),
    ]
